apiVersion: v1
kind: Secret
metadata:
  name: orderflow-secrets
type: Opaque
stringData:
  ORDER_DB_PASSWORD: REPLACE_ME_ORDER_DB_PASSWORD
  NOTIFICATION_DB_PASSWORD: REPLACE_ME_NOTIFICATION_DB_PASSWORD
